### PR TITLE
enhance website

### PR DESCRIPTION
**Pull request by lkwg82**
Hi,

I'd like to support your project with some contribution to enhance the website.

If you like it, I'm willing to do more. Have some ideas.

Cheers Lars

### CODE REVIEW

**Comment by calmh** [comment]
Cool, thanks! I think you may need some more magic for the github ribbon to work in IE, i.e. the conditional css include and perhaps the normalize css?

**Comment by calmh** [comment]
I don't think I agree with the shrinking of the logo though.

screen shot 2015-03-09 at 21 13 26

**Comment by lkwg82** [comment]
1. logo/font ... ok
2. Which IE version do you intend to support?

**Comment by calmh** [comment]
I don't know... Some reasonable version. :)

**Comment by lkwg82** [comment]
At work we limit our scope to all browser above 5% market share (market share based on customer visits). So you can take a look in google analytics.

With [modern.ie](https://www.modern.ie/en-us/virtualization-tools#downloads) I'll check against ie 8 and ie 9 ok? 

I like to exclude lower version, as I dont want to introduce technical debt ;).

**Comment by calmh** [comment]
Sounds perfectly fine to me. BTW, by that measure we could actually ignore IE completely, if we only care about the current demographics of the site. Which would of course be a mistake, but it still surprised me a little, even knowing that we cater to mostly geeks...

screen shot 2015-03-09 at 23 56 28

(sorry for the swedish, but I guess the numbers speak for themselves)

**Comment by lkwg82** [comment]
Ok, I dont do anything for IE.

**Comment by lkwg82** [comment]
When you still question IE support, add second dimension and type 'version' to add browser version.

**Comment by lkwg82** [comment]
I need the logo with security text as svg. After that I'm done so far.

**Comment by calmh** [comment]
So, this is now a 37 thousand line diff... Hang on while I parse it. :)

**Comment by calmh** [comment]
The readme lacks a step, `npm install` in website dir or grunt won't run. This installs a staggering

``` bash
jb@syno:~/src/github.com/syncthing/website (pr/10) $ npm list | wc -l
    2579
```

2579 (!) packages as dependencies... Grunt then aborts with a warning that I'm not sure what it means (images/bg.jpg is there);

```
jb@syno:~/src/github.com/syncthing/website (pr/10) $ grunt
Running "clean:0" (clean) task
>> 1 path cleaned.

Running "clean:1" (clean) task
>> 0 paths cleaned.

Running "uncss:dist" (uncss) task
ReferenceError: Can't find variable: $

  https://blockchain.info//Resources/wallet/pay-now-button.js:3
File tmp/tidy.css created: 176.59 kB → 14.33 kB

Running "cssmin:dist" (cssmin) task

Running "processhtml:dist" (processhtml) task

Running "htmlmin:dist" (htmlmin) task
Minified 2 files

Running "copy:main" (copy) task
Created 3 directories, copied 45 files

Running "imagemin:dist" (imagemin) task
Warning: Error: spawn ENOENT in file images/bg.jpg Use --force to continue.

Aborted due to warnings.


Execution Time (2015-03-12 13:01:49 UTC)
loading tasks  1.8s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 40%
uncss:dist     2.5s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 55%
cssmin:dist    81ms  ▇▇▇ 2%
copy:main      54ms  ▇▇ 1%
imagemin:dist  57ms  ▇▇ 1%
Total 4.5s
```

but does create a `www` dir.

All in all, the changes you've done are nice but I'm not sure about the rather involved compilation process required here. From what I could tell of inspecting the results, the one thing that made a noticable difference is the uncss (i think?) thing that minimizes the amount of css included - that cuts away most of bootstrap and fontawesome since we only use parts of them. I'm not fully convinced that's worth the hassle though...

**Comment by lkwg82** [comment]
1) Yes grunt as build tool introduces a lot. But as with each build tool it comes with some trade off. In the beginning it feels like overengineered. But in the end you walked the way alone and had to put everything in place manually. Ok you learned a lot. You learn you should had start with grunt to circumvent the trails of pain.

Grunt helps in case of image optimisation I did not start that: One source image and many specific output images to satisfy mobile and desktop devices.

If you think, why do you need that. This kind of stuff makes the different between the middle class and very good pages. http://timkadlec.com/2014/01/fast-enough/

It is a bit of picking low hanging fruits.

2) the uncss issue I did not notice before (I'll have look into).
3) imagemin ... I'll see, my output: https://gist.github.com/lkwg82/9c8a86f16a89fa657ac5

....

My perspective is from online-marketing to support google ranking (for almost no costs). And with grunt you can easily build up some content with a harmonized build-chain. 

My vision is that you 
- dont see at first sight, that syncthing is open source and software build in spare time.
- you can watch the people from the core team, so that you emotional can trust the software
- it is explained how it works with simple graphics
- you have some comparision table: btsync vs. syncthing, see http://www.similarweb.com/website/syncthing.net
- maybe we can start blogging each month some highlights

It is very vaque. But I see some room for marketing improvement.

Closing my explaination ... with this vision, I'd like to introduce grunt. To enable some next steps.

**Comment by lkwg82** [comment]
``` bash
$ grunt uncss
Running "uncss:dist" (uncss) task
ReferenceError: Can't find variable: $

  https://blockchain.info//Resources/wallet/pay-now-button.js:3
File tmp/tidy.css created: 176.59 kB → 14.33 kB

Done, without errors.


Execution Time (2015-03-12 20:55:51 UTC)
loading tasks  1.1s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 18%
uncss:dist     5.2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 82%
Total 6.3s
```

Phantomjs evaluates the pay-now-button.js and did not find early loaded jquery $ object, so it warns.
The order is correct. So I think this is an error in phantomjs.

**Comment by lkwg82** [comment]
> problem with imagemin:dist

Try removing the folder 'node_modules' and restart with 'npm install', I experienced continuing an aborted installation is not in the scope of npm ;)

**Comment by AudriusButkevicius** [comment]
I am not against tools which help us, but we should probably move the site to CI in this case, because I briefly tried to do all of this on Windows, and I can tell you that it's harder than it looks. I have to get a mingw compiler installed to compile node bindings for phantom and all sorts of exciting stuff.

**Comment by lkwg82** [comment]
Yeah, in case of having windows in the dev team, we should have a source of truth! CI seems good.

**Comment by lkwg82** [comment]
What is needed to complete and merge this?

**Comment by ghost** [comment]
What is the status for this pull request?

I'd like to add a Downloads page with download links that always provide the latest Github binaries for each specific architecture. However, I don't want to build on the current master if elements of this fork are to be merged first.

**Comment by calmh** [comment]
For me, this is too large and unwieldy to merge. I don't mind the path changes, the change to svg logos is nice, and so on, but the build tooling etc makes it unmergeable as it breaks the current process. That needs to be introduced more softly.

**Comment by ghost** [comment]
Ok, perhaps @lkwg82 changes can be put into a `dev` branch and keep `master` as html/css for now? Can just the html/css assets can be merged into main? Also, how does the build tooling break the current process?

**Comment by lkwg82** [comment]
@xHN35RQ agree
@calmh  I already thought of going back to the commit just before introducing grunt, to c4c9e312d05c09b9edf4e2c01becd6dd07f29472

I understand introducing grunt is a big step, maybe too fast. So what about everything until that commit?

**Comment by lkwg82** [comment]
I rebased just before grunt introduction.

**Comment by lkwg82** [comment]
this is still a static version, hope you are fine with that so far

**Comment by ghost** [comment]
Hello, what is the status of this pull request? I have some suggestions for the site but don't want to move forward until this pull request is merged so I don't have to re-do a bunch of work. Thanks.

**Comment by calmh** [comment]
Sorry, this had slipped under my radar once updated. I'll review!

**Comment by ghost** [comment]
> Sorry, this had slipped under my radar once updated. I'll review! 

:+1:

**Pull request merged**
