### PR TITLE
Decrease source resolution of images. code.jpg, rsa.jpg and

### PR DESCRIPTION
**Pull request by pebra**
Hey,

first of all, thanks for this awesome tool!

I just realized, that your page is ~3.3MB in size. You can get easily to a size of ~1.8MB just by decreasing the size of rsa.jpg, screenshot.jpg and coe.jpg, since they will always be of width 360px on the page.
I think this is especially useful for users who access your site with their mobile plan!

### CODE REVIEW

**Comment by calmh** [comment]
Hmm. I see them in twice that resolution, from a high DPI device. But still, they're not that big?

```
jb@syno:~/src/github.com/syncthing/website/images git:(master) $ du -sch *jpg
 72K    bg.jpg
 52K    code.jpg
 96K    rsa.jpg
 80K    screenshot.jpg
300K    total
```

**Comment by pebra** [comment]
You're totally right about "rsa" and "code"! Which suprises me is what du shows for me:

```
pebra ~/D/s/g/w/images> du -sch *jpg                                                                                    master
72K     bg.jpg
60K     code.jpg
96K     rsa.jpg
1012K   screenshot.jpg
1,3M    total
```

The website delivers that screenshot.jpg as well with about ~1MB size:
syncthing_loading_time

**Comment by calmh** [comment]
Ah, I actually had an old workspace checked out, sorry. Please do fix that one, that's excessive for sure, although I'd suggest aiming for 720 px on all of them.

**Comment by pebra** [comment]
Just did so, created a fresh PR

**Pull request closed without merging**
